version: '3'

services:
  web:
    image: nginx:alpine
    restart: always
    expose:
      - '80'
    volumes: 
      - ./static:/usr/share/nginx/html 
    environment:
      - VIRTUAL_HOST=static.local
      - LETSENCRYPT_HOST=static.local

networks:
  default:
    external:
      name: nginx-proxy
